**University of Science and Technology UST,  Zewail City**<br>
**CIE Program**<br>
**Computer Vision - CIE 552**<br>
**Lab Assignment #2**<br>

**Student Name:** Elsayed Mohammed Elsayed Mostafa <br>
**Student ID:**   201700316

## Imports

In [ ]:
import cv2
import numpy as np
from scipy.signal import convolve2d, correlate2d

## Utility functions

In [ ]:
def visualize_image(figure_name: str, img: np.ndarray):
    '''''
    A functions that visulaize the passed image using cv2 with a name for the figure
    @Parameters 
        figure_name: The figure title
        img: N-D array represents the image to be visulaized 
    @Author: Eng. Mohammed Elsayed (email: asmohamed@zewailcity.edu.eg)
    '''''
    cv2.imshow(figure_name, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [ ]:
def show_images(images, titles):
    '''''
    A functions that visulaize the passed image using cv2 with a name for the figure
    @Parameters 
        figure_name: The figure title
        img: N-D array represents the image to be visulaized 
    @Author: Eng. Mohammed Elsayed (email: asmohamed@zewailcity.edu.eg)
    '''''
    assert len(images) == len(titles)
    for title in titles:
        cv2.namedWindow(title, cv2.WINDOW_NORMAL)
    
    for title, img in zip(titles, images):
        cv2.imshow(title, img)

    cv2.waitKey(0)
    cv2.destroyAllWindows()

## Creating filters functions

### Mean filter

In [ ]:
def create_mean_filter(ksize):
    '''''
    - A functions creates a mean filter of an arbitrary odd size (ksize*ksize)
    @Parameters 
        ksize: odd integer that represents the length and width of the mean filter
    @Returns:
        mean_filter: The obtained mean filter
    '''''
    # Assert that the length is odd
    assert ksize%2 != 0
    # Create the filter
    return np.ones(shape=(ksize,ksize))/(ksize**2)


### Gaussian filter

**The formula for gaussian filter is:**
$$G(x, y) = A e^{\frac{-(x - \mu_x)^2}{2 \sigma_x^2} + \frac{-(y - \mu_y)^2}{2 \sigma_y^2}}$$
* $G(x, y)$ is the Gaussian kernel
* $\mu$ is the mean 
* $\sigma^2$ is the variance

**Instead of having different values of standard deviations for x and y, the tradition is to have the same value for both. In addition the value for A is usually set by ($\frac{1}{\sqrt{2\pi}\sigma}$)**<br>
*Reference:* https://homepages.inf.ed.ac.uk/rbf/HIPR2/gsmooth.htm

In [ ]:
def create_gaussian_filter(ksize, sigma=(1,1)):
    '''''
    - A functions creates a gaussian filter of an arbitary size (ksize*ksize)
    @Parameters: 
        ksize: odd integer that represents the length and width of the mean filter
        sigma: a tuble/list of 2 elements represents (x_sigma, y_sigma), where sigma is the standard deviation of each direction
               However, the default value if 1 for both.
    @Returns:
        gaussian_filter: The obtained mean filter
    '''''
    assert ksize % 2 != 0
    
    # For the value of A, in case of sigma_x != sigma_y, I'll use the mean of both sigmas to evaluate the value of A
    A = 1/(2*np.pi*np.mean(sigma))
    # Creating a linspace for each direction (2D)
    x = np.linspace(start = 0, stop = ksize-1, num = ksize)
    y = x.copy()
    # Calculate the mean of each direction (One value as they're the same linspace)
    mu = np.mean(x)
    # Create the meshgrid that represents the 2D values as a grid
    X, Y = np.meshgrid(x,y)
    # Applying the gaussian filter equation on the created grid
    gaussian_filter = A * np.exp((-(X-mu)**2)/(2*sigma[0]) + (-(Y-mu)**2)/(2*sigma[1])) 
    return gaussian_filter

## Reading the image

In [ ]:
# Speicify the image path (just the name if it is in the same directory as the notebook/script)
img_path = 'mona_lisa.jpg'
# Read the image using openCV
img = cv2.imread(img_path,cv2.IMREAD_GRAYSCALE)
# Printing the image shape
print('image shape = ',img.shape)
# Visualizing the image
visualize_image('original_image', img)

image shape =  (530, 350)


In [ ]:
# Visualize the original image with 3 blurred images at different sizes
mean_blur_img1 = cv2.blur(img, ksize=(5, 5), borderType=cv2.BORDER_CONSTANT)
visualize_image('Mean blur', mean_blur_img1)

## Creating and applying the filters

### Mean filter

In [ ]:
# Create the filter (kernel)
mean_filter = create_mean_filter(5)
print(mean_filter)

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


In [ ]:
# Correlating the filter with the image and visulaizing the output 
blurred_img = correlate2d(img, mean_filter,'same').astype(np.uint8)
visualize_image('mean_filter',blurred_img)

### Gaussian filter

In [ ]:
# Create the filter (kernel)
gaussian_filter = create_gaussian_filter(ksize=5, sigma=(3,3))
print(gaussian_filter)

[[0.01398426 0.02305615 0.02723762 0.02305615 0.01398426]
 [0.02305615 0.03801317 0.04490725 0.03801317 0.02305615]
 [0.02723762 0.04490725 0.05305165 0.04490725 0.02723762]
 [0.02305615 0.03801317 0.04490725 0.03801317 0.02305615]
 [0.01398426 0.02305615 0.02723762 0.02305615 0.01398426]]


In [ ]:
# Correlating the filter with the image and visulaizing the output 
gauused_img = correlate2d(img, gaussian_filter,'same').astype(np.uint8)
visualize_image('gaussian_filter',gauused_img)

## Testing

### Mean filter

#### Testing for different kernel sizes

In [ ]:
# Speicfy the kernel size for each test
ksizes = [3,5,7,13,21]
# Creating the suitable title for each kernel size
imgs_titles = ['mean filter of k='+str(k) for k in ksizes]
# Applying the mean filters
filtered_imgs = [correlate2d(img,create_mean_filter(ksize=k)).astype(np.uint8) for k in ksizes]
# Visualizing the images
show_images(filtered_imgs, imgs_titles)

### Gaussian filter

#### Testing for different kernel sizes

In [ ]:
# Speicfy the kernel size, sigma_x, sigmas_y for each test
ksizes = [3,5,7,13,21]
sigma = (3, 3)

# Creating the suitable title for each kernel size
imgs_titles = ['gaussian filter of k= {}'.format(k) for k in ksizes]
# Applying the mean filters
filtered_imgs = [correlate2d(img,create_gaussian_filter(ksize=k, sigma=sigma)).astype(np.uint8) for k in ksizes]
# Visualizing the images
show_images(filtered_imgs, imgs_titles)

***From the results, I choose k=5 to continue in the following process.***

#### Testing for different values of $\sigma$

In [ ]:
# Speicfy the kernel size, sigma_x, sigmas_y for each test
k = 5
sigmas_x = [0.5, 1, 4, 10]
sigmas_y = sigmas_x.copy()
# Creating the suitable title for each kernel size
imgs_titles = ['({},{})'.format(sigma_x, sigma_y) for sigma_x in sigmas_x for sigma_y in sigmas_y]
# Applying the mean filters
filtered_imgs = [correlate2d(img,create_gaussian_filter(k, (sigma_x,sigma_y))).astype(np.uint8) for sigma_x in sigmas_x for sigma_y in sigmas_y]
# Visualizing the images
show_images(filtered_imgs, imgs_titles)

#### Insights

> The more difference between $\sigma_x$ and $\sigma_y$, the more tendency of the filtered image towards black. This happens because the value of A is closer less in such cases compared to the same value os $\sigma_x$ ($\sigma_y$) with lower value of  $\sigma_y$ ($\sigma_x$)

> The higher values of $\sigma$, the lower value of A and hence, the more tendency of the filtered image towards black color. 